### ISSUE TITLE
argument groups duplicate arguments

### ISSUE THREAD

**Issue by croth1** [ribozz/sphinx-argparse#49] opened 2017-02-14 06:37 UTC
This parser

```python
def create_parser2():
    parser = argparse.ArgumentParser('foo')
    parser.add_argument('--foo', help='foo help')
    grp1 = parser.add_argument_group('bar options')
    grp1.add_argument('--bar', help='bar help')
    grp2 = parser.add_argument_group('bla options')
    grp2.add_argument('--bla', help='bla help')
    return parser
```

gives this command line help:

```usage: foo [-h] [--foo FOO] [--bar BAR] [--bla BLA]

optional arguments:
  -h, --help  show this help message and exit
  --foo FOO   foo help

bar options:
  --bar BAR   bar help

bla options:
  --bla BLA   bla help
```

but renders to following sphinx output:

```
.. argparse::
  :module: foo
  :func: create_parser2
  :prog: foo
  :nodefaultconst:

```
```
   usage: foo [-h] [--foo FOO] [--bar BAR] [--bla BLA]

optional arguments
   --foo

   foo help

bar options
   --foo

   foo help

   --bar

   bar help

bla options
   --foo

   foo help

   --bar

   bar help

   --bla

   bla help
```

**Comment by croth1** [comment] 2017-02-18 10:58
The error is probably here: https://github.com/ribozz/sphinx-argparse/blob/master/sphinxarg/ext.py#L70

The initialization of `items` should probably go into the loop iterating over the argument groups.

**Comment by dpryan79** [comment] 2017-02-22 20:56
You're correct about the cause of this. I'd also like to fix how positional arguments in argument groups are handled (they're partially duplicated at the moment).

**Comment by dpryan79** [comment] 2017-02-23 14:31
This is now fixed in the `develop` branch. I'll post a new version on Monday at the latest with this.

**Comment by dpryan79** [comment] 2017-02-24 13:44
0.1.17 is now available on pypi.

**Closed by dpryan79** 2017-02-24 13:44 UTC
Labels: bug
